#!/bin/bash

if [  ! -d "./scripts" ]; then
    echo "please run from project directory"
    exit 1
fi

csplit src/hafas/hafasController.ts /Range/ {1}

echo "  // beginOfRange" > xx01
node build/generator/index.js --file ./types/hafas-client/index.d.ts --method journeys -x JourneysOptions.arrival JourneysOptions.products JourneysOptions.earlierThan JourneysOptions.laterThan JourneysOptions.when >> xx01
node build/generator/index.js --file ./types/hafas-client/index.d.ts --method trip  >> xx01
node build/generator/index.js --file ./types/hafas-client/index.d.ts --method departures  >> xx01
node build/generator/index.js --file ./types/hafas-client/index.d.ts --method locations >> xx01
node build/generator/index.js --file ./types/hafas-client/index.d.ts --method stop  >> xx01
node build/generator/index.js --file ./types/hafas-client/index.d.ts --method nearby -x Location.type Location.id Location.name Location.poi Location.address Location.altitude Location.distance >> xx01
node build/generator/index.js --file ./types/hafas-client/index.d.ts --method reachableFrom -x Location.type Location.id Location.name Location.poi Location.altitude ReachableFromOptions.when ReachableFromOptions.products >> xx01
node build/generator/index.js --file ./types/hafas-client/index.d.ts --method radar -x RadarOptions.products >> xx01

cat xx00 xx01 xx02 > src/hafas/hafasController.ts

rm xx0*

